name: decision_maker_pro
description: "Interactive decision-making app with randomization tools - Let chance decide for you!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  font_awesome_flutter: ^10.7.0
  icons_plus: ^5.0.0

  # State Management
  flutter_riverpod: ^2.5.1  # Removed duplicate provider dependency
  flutter_bloc: ^8.1.6
  get: ^4.6.6

  # Device Sensors & Input
  sensors_plus: ^6.1.1

  # Local Storage & Database
  shared_preferences: ^2.3.2  # Removed duplicate entry
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1

  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0

  # Animation & Graphics
  lottie: ^3.1.2
  rive: ^0.13.15
  flutter_animate: ^4.5.0
  
  # Game Engine & Physics
  flame: ^1.17.0
  flame_forge2d: ^0.16.0+2  # Box2D physics for Flame
  forge2d: ^0.12.2  # Core Box2D physics

  # Audio & Haptics
  audioplayers: ^6.1.0
  just_audio: ^0.9.39
  vibration: ^2.0.0
  flutter_vibrate: ^1.3.0

  # Speech
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.2

  # Firebase Services
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # Backend Alternatives
  supabase_flutter: ^2.8.0
  appwrite: ^14.0.0

  # Monetization
  in_app_purchase: ^3.2.0

  # Device Info & Permissions
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1

  # Utilities
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  package_info_plus: ^8.0.2

  # Cryptography & Security
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  # Custom Fragment Shaders
  shaders:
    - shaders/wheel_glow.frag
    - shaders/coin_shimmer.frag
    - shaders/dice_sparkle.frag
    - shaders/number_pulse.frag

  # Assets
  assets:
    # Animations
    - assets/animations/
    
    # Icons
    - assets/icons/
    - assets/icons/premium/
    
    # Images
    - assets/images/
    - assets/images/dice_faces/
    
    # Sounds
    - assets/sounds/